wandb_project_name: MMPpp
logdir: 'results/toy/exp3'
logger: 
  type: base
  endwith: ['@', '#']
model:
  encoder:
    arch: fc_vec
    l_hidden: [256, 256, 256, 256, ]
    activation: ['elu', 'elu', 'elu', 'elu', ]
    out_activation: 'linear'
  decoder:
    arch: fc_vec
    l_hidden: [256, 256, 256, 256, ]
    activation: ['elu', 'elu', 'elu', 'elu', ]
    out_activation: 'linear'
  x_dim: 40
  z_dim: 2
  dof: 2
  b: 20
  via_points: [[0.8, 0.8], [-0.8, -0.8]]
data:
  training:
    dataset: Toy
    root: datasets/EXP3
    batch_size: 5
    n_workers: 4
    split: training
    shuffle: True
  validation:
    dataset: Toy
    root: datasets/EXP3
    batch_size: 5
    n_workers: 4
    split: validation
    shuffle: True
trainer: base
training:
  n_epoch: 3000
  optimizer:
    name: 'adam'
    lr: 0.0001
  print_interval: 100
  val_interval: 100
  eval_interval: 100
  besteval_key: mmd_
  eval_n_components: 4
  visualize_interval: null